language: node_js

node_js:
  - "10"
python:
  - "2.7"
  - "3.4"

before_install:
  - gem update --system
  - sudo apt-get install -y python3.4
  - sudo apt-get install --upgrade -y python-pip
  - sudo apt-get install jq
  - sudo pip install --user virtualenv

  - virtualenv my_py3 --python=/usr/bin/python3.4
  - source my_py3/bin/activate
  - pip install --upgrade awscli
  - pip install --upgrade awsebcli

before_script:
  - aws configure set aws_access_key_id AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key AWS_SECRET_ACCESS_KEY
  - aws configure set default.region AWS_REGION
  - aws configure set metadata_service_timeout 1200
  - aws configure set metadata_service_num_attempts 3
  - aws configure list

script:
  - if [ "$TRAVIS_BRANCH" == "test-deploy-script" ]; then
      eb init -p docker GoodGunReceiver;
      travis_wait 30 eb deploy $EB_ENV_NAME; 
    fi
